name: Java CI with Maven
on:
  push:
    branches: [ "master" ]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v4

    - name: Increase version
      run: mvn versions:set -DnewVersion=1.0.${{github.run_number}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        build-args: VERSION=${{github.run_number}}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:${{github.run_number}} , ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:latest


  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
