name: Java CI with Maven
on:
  push:
    branches: [ "master" ]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v4

    - name: Increase version
      run: mvn versions:set -DnewVersion=1.0.${{github.run_number}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        build-args: VERSION=${{github.run_number}}
        push: true
        tag: ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:${{github.run_number}}
        push: true
        tag: ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:latest
