name: Java CI with Maven
on:
  push:
    branches: [ "master" ]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v4

    - name: Increase version
      run: mvn versions:set -DnewVersion=1.0.${{github.run_number}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        build-args: VERSION=${{github.run_number}}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:${{github.run_number}} , ${{ secrets.DOCKERHUB_USERNAME }}/maven_project:latest


  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false
